package com.todolist.api.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBDocument
@DynamoDBTable(tableName = "task")
public class Task {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private Long id;

    @DynamoDBAttribute
    private String taskDescription;

}
