package com.todolist.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "task")
public class Task {

    private String id;
    private String taskDescription;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "task_description")
    public String getTaskDescription() {
        return taskDescription;
    }

    @DynamoDBAttribute(attributeName = "task_description")
    public void setTaskDescription(String taskDescription) {
        this.taskDescription = taskDescription;
    }
}
